linters-settings:
  dupl:
    threshold: 100
  govet:
    check-shadowing: true
    settings:
      printf:
        funcs:
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
  misspell:
    locale: US

linters:
  disable-all: true
  enable:
    - errcheck # checking for unchecked errors in Go programs
    - gosimple # simplifying code
    - govet # report suspicious configurations such as Printf calls whose arguments do not match the format string
    - ineffassign # detects when assignments to existing variables are not used
    - staticcheck # a Go vet on steroids, applying a ton of static analysis checks
    - typecheck # parse and type check Go code
    - unused # checks Go code for unused constants, variables, functions and types
    - dupl # tool for code clone detection
    - unconvert # remove unnecessary type conversions
    - whitespace # tool for detection of leading and trailing whitespace

run:
  timeout: 15m
  go: '1.18'
