name: Main
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RUN_FROM_CI: "true"
      GOLANG_IMAGE_VERSION: "1.18.3"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GOLANG_IMAGE_VERSION }}
          cache: true
          cache-dependency-path: library/go.mod
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
            ~/.cache/golangci-lint
          key: go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            go-
      - uses: actions/cache@v3
        with:
          path: |
            ./bin
          key: bin
          restore-keys: |
            bin
      - run: make setup
      - run: make lint
      - run: make test
